/* Generated By:JavaCC: Do not edit this line. DefaultWikiParserConstants.java */
package hu.sztaki.sztakipediaparser.wiki.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DefaultWikiParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OBRACKET = 1;
  /** RegularExpression Id. */
  int OBRACKET2 = 2;
  /** RegularExpression Id. */
  int H_WHITESPACE = 3;
  /** RegularExpression Id. */
  int V_WHITESPACE = 4;
  /** RegularExpression Id. */
  int EXT_CLOSE = 5;
  /** RegularExpression Id. */
  int EXT_URL = 6;
  /** RegularExpression Id. */
  int EXT_H_WHITESPACE = 7;
  /** RegularExpression Id. */
  int EXT_ALIAS = 8;
  /** RegularExpression Id. */
  int EXT_ALIAS_CLOSE = 9;
  /** RegularExpression Id. */
  int INT_CLOSE = 10;
  /** RegularExpression Id. */
  int INT_URL = 11;
  /** RegularExpression Id. */
  int INT_PIPE = 12;
  /** RegularExpression Id. */
  int INT_ALIAS_CLOSE = 13;
  /** RegularExpression Id. */
  int INT_ALIAS = 14;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_EXTERNAL_LINK = 1;
  /** Lexical state. */
  int IN_EXTERNAL_LINK_ALIAS = 2;
  /** Lexical state. */
  int IN_INTERNAL_LINK = 3;
  /** Lexical state. */
  int IN_INTERNAL_LINK_ALIAS = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"[\"",
    "\"[[\"",
    "<H_WHITESPACE>",
    "<V_WHITESPACE>",
    "\"]\"",
    "<EXT_URL>",
    "<EXT_H_WHITESPACE>",
    "<EXT_ALIAS>",
    "\"]\"",
    "\"]]\"",
    "<INT_URL>",
    "\"|\"",
    "\"]]\"",
    "<INT_ALIAS>",
  };

}
